import { PDFDocument, StandardFonts, rgb } from "pdf-lib";

const TEAL = rgb(0.059, 0.463, 0.431); // #0f766e
const INK = rgb(0.06, 0.09, 0.16);
const MUTED = rgb(0.45, 0.5, 0.55);
const LINE = rgb(0.9, 0.92, 0.93);

const peso = (c: number) => "PHP " + (c / 100).toLocaleString("en-PH", { minimumFractionDigits: 2, maximumFractionDigits: 2 });

export interface DocLine {
  description: string;
  qty: number;
  unit_centavos: number;
  total_centavos: number;
}

export interface DocData {
  docLabel: string; // "QUOTATION" | "INVOICE"
  number: string;
  shopName: string;
  shopContact?: string | null;
  customerName: string;
  customerContact?: string | null;
  date: string;
  dueDate?: string | null;
  lines: DocLine[];
  subtotal_centavos: number;
  deliveryFee_centavos?: number;
  discount_centavos: number;
  total_centavos: number;
  amountPaid_centavos?: number;
  footer?: string | null;
}

/** Build a simple branded A4 document and return the PDF bytes. */
export async function buildDocument(d: DocData): Promise<Uint8Array> {
  const pdf = await PDFDocument.create();
  const page = pdf.addPage([595, 842]); // A4
  const font = await pdf.embedFont(StandardFonts.Helvetica);
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold);
  const { width } = page.getSize();
  const M = 48;
  let y = 800;

  const text = (
    s: string,
    x: number,
    yy: number,
    opts: { size?: number; font?: typeof font; color?: typeof INK } = {},
  ) => page.drawText(s ?? "", { x, y: yy, size: opts.size ?? 10, font: opts.font ?? font, color: opts.color ?? INK });

  const right = (
    s: string,
    xRight: number,
    yy: number,
    opts: { size?: number; font?: typeof font; color?: typeof INK } = {},
  ) => {
    const f = opts.font ?? font;
    const size = opts.size ?? 10;
    text(s, xRight - f.widthOfTextAtSize(s ?? "", size), yy, opts);
  };

  // Header
  text(d.shopName, M, y, { size: 20, font: bold, color: TEAL });
  right(d.docLabel, width - M, y, { size: 20, font: bold, color: INK });
  y -= 16;
  if (d.shopContact) text(d.shopContact, M, y, { size: 9, color: MUTED });
  right(`# ${d.number}`, width - M, y, { size: 10, color: MUTED });
  y -= 30;

  page.drawLine({ start: { x: M, y }, end: { x: width - M, y }, thickness: 1, color: LINE });
  y -= 24;

  // Parties
  text("BILL TO", M, y, { size: 8, font: bold, color: MUTED });
  right("DATE", width - M, y, { size: 8, font: bold, color: MUTED });
  y -= 14;
  text(d.customerName, M, y, { size: 11, font: bold });
  right(d.date, width - M, y, { size: 10 });
  y -= 14;
  if (d.customerContact) text(d.customerContact, M, y, { size: 9, color: MUTED });
  if (d.dueDate) right(`Due ${d.dueDate}`, width - M, y, { size: 9, color: MUTED });
  y -= 30;

  // Table header
  const colQty = 330;
  const colUnit = 430;
  const colTotal = width - M;
  page.drawRectangle({ x: M, y: y - 6, width: width - M * 2, height: 22, color: rgb(0.96, 0.97, 0.97) });
  text("DESCRIPTION", M + 8, y, { size: 8, font: bold, color: MUTED });
  right("QTY", colQty, y, { size: 8, font: bold, color: MUTED });
  right("UNIT", colUnit, y, { size: 8, font: bold, color: MUTED });
  right("AMOUNT", colTotal, y, { size: 8, font: bold, color: MUTED });
  y -= 24;

  for (const line of d.lines) {
    text(line.description.slice(0, 60), M + 8, y, { size: 10 });
    right(String(line.qty), colQty, y, { size: 10 });
    right(peso(line.unit_centavos), colUnit, y, { size: 10 });
    right(peso(line.total_centavos), colTotal, y, { size: 10 });
    y -= 20;
    page.drawLine({ start: { x: M, y: y + 6 }, end: { x: width - M, y: y + 6 }, thickness: 0.5, color: LINE });
  }
  y -= 10;

  // Totals
  const totalsX = 360;
  const totalRow = (labelText: string, value: string, opts: { bold?: boolean } = {}) => {
    text(labelText, totalsX, y, { size: opts.bold ? 11 : 10, font: opts.bold ? bold : font, color: opts.bold ? INK : MUTED });
    right(value, colTotal, y, { size: opts.bold ? 12 : 10, font: opts.bold ? bold : font });
    y -= opts.bold ? 22 : 18;
  };
  totalRow("Subtotal", peso(d.subtotal_centavos));
  if (d.deliveryFee_centavos) totalRow("Delivery fee", peso(d.deliveryFee_centavos));
  if (d.discount_centavos) totalRow("Discount", "- " + peso(d.discount_centavos));
  page.drawLine({ start: { x: totalsX, y: y + 8 }, end: { x: width - M, y: y + 8 }, thickness: 1, color: LINE });
  y -= 4;
  totalRow("TOTAL", peso(d.total_centavos), { bold: true });
  if (d.amountPaid_centavos != null) {
    totalRow("Paid", peso(d.amountPaid_centavos));
    totalRow("Balance", peso(d.total_centavos - d.amountPaid_centavos), { bold: true });
  }

  // Footer
  if (d.footer) {
    text(d.footer, M, 60, { size: 9, color: MUTED });
  }
  text("Generated by PrintOS", M, 40, { size: 8, color: LINE });

  return pdf.save();
}
