-- ============================================================
-- PrintOS — Supabase Storage Buckets
--
-- | Bucket               | Purpose                              | Access                |
-- |----------------------|--------------------------------------|-----------------------|
-- | order-files          | Designer-uploaded layout files       | Private (signed URLs) |
-- | thumbnails           | Auto-generated file thumbnails       | Public                |
-- | quotation-pdfs       | Generated quotation PDFs             | Private (signed URLs) |
-- | invoice-pdfs         | Generated invoice PDFs               | Private (signed URLs) |
-- | qr-codes             | Generated QR code images             | Public                |
-- | org-logos            | Tenant brand logos                   | Public                |
-- | revision-references  | Files attached to revision requests  | Private               |
-- | chat-attachments     | Files sent in order chat             | Private               |
--
-- Private buckets are accessed via signed URLs generated by the
-- backend (service role); no storage.objects policies are created
-- here for them.
-- ============================================================

insert into storage.buckets (id, name, public) values
  ('order-files',         'order-files',         false),
  ('thumbnails',          'thumbnails',          true),
  ('quotation-pdfs',      'quotation-pdfs',      false),
  ('invoice-pdfs',        'invoice-pdfs',        false),
  ('qr-codes',            'qr-codes',            true),
  ('org-logos',           'org-logos',           true),
  ('revision-references', 'revision-references', false),
  ('chat-attachments',    'chat-attachments',    false)
on conflict (id) do nothing;
