-- ============================================================
-- PrintOS — Storage object policies
--
-- The web app uploads/reads files as the authenticated user, so
-- storage.objects needs RLS policies. Convention: the FIRST folder
-- segment of every object path is the owning organization's id
-- (e.g. "order-files/<org_id>/<order_id>/v1-layout.pdf").
--
-- Staff get full access to their own org's objects across all
-- PrintOS buckets. Portal customers are served via signed URLs
-- generated by the backend (service role), as documented in the
-- buckets migration.
--
-- Wrapped in a conditional so the migration also runs outside
-- Supabase (e.g. plain-Postgres CI) where storage.objects and the
-- authenticated role don't exist.
-- ============================================================

do $$
begin
  if exists (
    select 1 from information_schema.tables
    where table_schema = 'storage' and table_name = 'objects'
  ) and exists (
    select 1 from pg_roles where rolname = 'authenticated'
  ) then
    execute $p$
      create policy "printos_staff_manage_org_objects" on storage.objects
        for all to authenticated
        using (
          bucket_id in (
            'order-files','thumbnails','quotation-pdfs','invoice-pdfs',
            'qr-codes','org-logos','revision-references','chat-attachments'
          )
          and (storage.foldername(name))[1] = public.user_organization_id()::text
          and public.user_is_staff()
        )
        with check (
          bucket_id in (
            'order-files','thumbnails','quotation-pdfs','invoice-pdfs',
            'qr-codes','org-logos','revision-references','chat-attachments'
          )
          and (storage.foldername(name))[1] = public.user_organization_id()::text
          and public.user_is_staff()
        )
    $p$;
  end if;
end;
$$;
